name: generators
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.4.3
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  build: 2.4.1
  source_gen: 1.5.0
  collection: any
  flutter_inappwebview_internal_annotations: ^1.2.0
    # path: ../flutter_inappwebview_internal_annotations

dev_dependencies:
  build_runner: 2.4.9
  build_test: 2.2.2
  test: 1.25.5
